export const PROPERTY_STATUSES = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  SETUP: 'SETUP',
  UNDER_MAINTENANCE: 'UNDER_MAINTENANCE',
  CLOSED: 'CLOSED',
} as const;

export const PROPERTY_TYPES = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
  MIXED: 'MIXED',
} as const;

export const ROOM_TYPES = {
  PRIVATE: 'PRIVATE',
  DOUBLE_SHARING: 'DOUBLE_SHARING',
  TRIPLE_SHARING: 'TRIPLE_SHARING',
  FOUR_SHARING: 'FOUR_SHARING',
  SIX_SHARING: 'SIX_SHARING',
} as const;

export const ROOM_SHARING_CAPACITY: Record<string, number> = {
  PRIVATE: 1,
  DOUBLE_SHARING: 2,
  TRIPLE_SHARING: 3,
  FOUR_SHARING: 4,
  SIX_SHARING: 6,
};

export const ROOM_STATUSES = {
  AVAILABLE: 'AVAILABLE',
  PARTIALLY_OCCUPIED: 'PARTIALLY_OCCUPIED',
  FULLY_OCCUPIED: 'FULLY_OCCUPIED',
  UNDER_MAINTENANCE: 'UNDER_MAINTENANCE',
  INACTIVE: 'INACTIVE',
} as const;

export const BED_STATUSES = {
  AVAILABLE: 'AVAILABLE',
  OCCUPIED: 'OCCUPIED',
  RESERVED: 'RESERVED',
  UNDER_MAINTENANCE: 'UNDER_MAINTENANCE',
  BLOCKED: 'BLOCKED',
} as const;

export const TENANT_STATUSES = {
  LEAD: 'LEAD',
  VISIT_SCHEDULED: 'VISIT_SCHEDULED',
  VISITED: 'VISITED',
  ROOM_FINALIZED: 'ROOM_FINALIZED',
  PENDING_COMPLIANCE: 'PENDING_COMPLIANCE', // deposit/kyc/agreement tracked via boolean flags
  DEPOSIT_PENDING: 'DEPOSIT_PENDING',        // @deprecated
  KYC_PENDING: 'KYC_PENDING',               // @deprecated
  ACTIVE: 'ACTIVE',
  NOTICE_PERIOD: 'NOTICE_PERIOD',
  MOVED_OUT: 'MOVED_OUT',
  ARCHIVED: 'ARCHIVED',
  REJECTED: 'REJECTED',
} as const;

/**
 * Valid status transitions for tenant lifecycle.
 * PENDING_COMPLIANCE is the unified pre-active compliance state.
 * DEPOSIT_PENDING and KYC_PENDING are kept for backward compatibility only.
 */
export const TENANT_STATUS_TRANSITIONS: Record<string, string[]> = {
  LEAD:                ['VISIT_SCHEDULED', 'REJECTED'],
  VISIT_SCHEDULED:     ['VISITED', 'LEAD', 'REJECTED'],
  VISITED:             ['ROOM_FINALIZED', 'REJECTED'],
  ROOM_FINALIZED:      ['PENDING_COMPLIANCE', 'ACTIVE', 'DEPOSIT_PENDING', 'KYC_PENDING', 'VISITED'],
  PENDING_COMPLIANCE:  ['ACTIVE'],
  DEPOSIT_PENDING:     ['ACTIVE', 'KYC_PENDING', 'PENDING_COMPLIANCE', 'ROOM_FINALIZED'],
  KYC_PENDING:         ['ACTIVE', 'DEPOSIT_PENDING', 'PENDING_COMPLIANCE'],
  ACTIVE:              ['NOTICE_PERIOD'],
  NOTICE_PERIOD:       ['MOVED_OUT', 'ACTIVE'],   // allow cancelling notice
  MOVED_OUT:           ['ARCHIVED'],
  ARCHIVED:            [],
  REJECTED:            [],
};

export const KYC_STATUSES = {
  PENDING: 'PENDING',
  SUBMITTED: 'SUBMITTED',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
} as const;

export const DEPOSIT_STATUSES = {
  PENDING: 'PENDING',
  PARTIALLY_PAID: 'PARTIALLY_PAID',
  PAID: 'PAID',
  REFUNDED: 'REFUNDED',
  PARTIALLY_REFUNDED: 'PARTIALLY_REFUNDED',
  FORFEITED: 'FORFEITED',
} as const;

export const COMPLAINT_CATEGORIES = {
  MAINTENANCE: 'MAINTENANCE',
  PLUMBING: 'PLUMBING',
  ELECTRICAL: 'ELECTRICAL',
  HOUSEKEEPING: 'HOUSEKEEPING',
  SECURITY: 'SECURITY',
  FOOD: 'FOOD',
  WIFI: 'WIFI',
  NOISE: 'NOISE',
  OTHER: 'OTHER',
} as const;

export const COMPLAINT_STATUSES = {
  OPEN: 'OPEN',
  ASSIGNED: 'ASSIGNED',
  IN_PROGRESS: 'IN_PROGRESS',
  RESOLVED: 'RESOLVED',
  REOPENED: 'REOPENED',
  CLOSED: 'CLOSED',
  REJECTED: 'REJECTED',
} as const;

/**
 * Valid transitions for complaint workflow.
 * REOPENED re-enters the active workflow from RESOLVED.
 */
export const COMPLAINT_STATUS_TRANSITIONS: Record<string, string[]> = {
  OPEN:        ['ASSIGNED', 'IN_PROGRESS', 'REJECTED', 'CLOSED'],
  ASSIGNED:    ['IN_PROGRESS', 'RESOLVED', 'REJECTED'],
  IN_PROGRESS: ['RESOLVED', 'CLOSED', 'REJECTED'],
  RESOLVED:    ['REOPENED', 'CLOSED'],
  REOPENED:    ['ASSIGNED', 'IN_PROGRESS', 'RESOLVED', 'CLOSED'],
  CLOSED:      [],
  REJECTED:    [],
};

export const PRIORITY_LEVELS = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  URGENT: 'URGENT',
} as const;

export const PRIORITY_WEIGHT: Record<string, number> = {
  LOW: 1,
  MEDIUM: 2,
  HIGH: 3,
  URGENT: 4,
};

export const TRANSFER_REASONS = {
  TENANT_REQUEST:    'TENANT_REQUEST',
  UPGRADE:           'UPGRADE',
  DOWNGRADE:         'DOWNGRADE',
  MAINTENANCE:       'MAINTENANCE',
  ROOMMATE_CONFLICT: 'ROOMMATE_CONFLICT',
  OPERATOR_DECISION: 'OPERATOR_DECISION',
  OTHER:             'OTHER',
} as const;

